### ISSUE TITLE
Unable to connect wallet to PolyPup UI  (Brave Browser)

### ISSUE THREAD

**Issue by frozenfire7** [PolyPup-Farm/polypup-ui-alpha-testers#1]
Unable to connect wallet to PolyPup UI after multiple attempts.   Button highlight appears on click but no other response from UI 

Browser: Brave
Wallet: Metamask

![image](https://user-images.githubusercontent.com/1440707/131282975-772ed994-152e-4e58-a8e3-907327167cea.png)

![image](https://user-images.githubusercontent.com/1440707/131283277-f7089240-ab6d-4a6d-a654-3e6414dc2990.png)

**Comment by Polypup** [comment]
We do not support this yet but can look into adding it 👍

**Comment by shoegaze503** [comment]
I'm using Brave Browser w/o issue.

**Comment by frozenfire7** [comment]
working now on my end - maybe issue was specific to my machine. closing out
