### ISSUE TITLE
Horizontal Overflow Issue

### ISSUE THREAD

**Issue by neothon** [PolyPup-Farm/polypup-ui-alpha-testers#11]
A particular row div is overflowing on the X axis which is causing a huge horizontal scroll. Attached image for refrence.

![image](https://user-images.githubusercontent.com/89765091/131295119-4c7df383-1e2a-4da0-9ebd-554ddcc031ab.png)

**Comment by Polypup** [comment]
will be fixed with #12

**Comment by Polypup** [comment]
removed this to be added in #12
