### ISSUE TITLE
(BUG) When clicking on project, I am brought to the bottom of the page

### ISSUE THREAD

**Issue by Chaney08** [PolyPup-Farm/polypup-ui-alpha-testers#15]
Whenever I click on a project I am immediately brought to the bottom of the page, this causes me to look at a page with nothing for a few seconds, instead I should be kept at the top so I can see the loading bar to indicate that the page is loading and this is not an error. See attached screenshot for what I see after clicking on a project, you will notice I cannot see the loading bar.

![image](https://user-images.githubusercontent.com/4929460/131325328-a075b7ad-8544-48bf-9d0e-4a58e9fe0837.png)

**Comment by Chaney08** [comment]
P.S - I cannot add Labels to indicate if this is a bug or feature request.

**Comment by Polypup** [comment]
Yes, I saw this, thank you. Will make note and fix it.

**Comment by Polypup** [comment]
fixed.
