### ISSUE TITLE
Dividends section not listed in PolyPup BALL (and other farms)

### ISSUE THREAD

**Issue by shoegaze503** [PolyPup-Farm/polypup-ui-alpha-testers#2]
Feature Request ::

It'd be nice to be able to see the dividends section of the various farms.  It seems that only pool and farm section are listed.

**Comment by Polypup** [comment]
Probably not going to happen because those are completely different smart contracts that don't connect with the masterchef contract. Our main focus is on the masterchef.

**Comment by shoegaze503** [comment]
Sounds good - thanks for quick reply.
