### ISSUE TITLE
Farm Details Page - Handling Dual Token Yield Farms (example Stadium Arcadium, PolyPulsar)

### ISSUE THREAD

**Issue by frozenfire7** [PolyPup-Farm/polypup-ui-alpha-testers#25]
Currently, appears that UI only partially handles dual token ecosystem.

For example in stadium arcadium there are two tokens "MyFriends" + Arcadium but only see top level stats for arcadium and LP don't reflect myfriend emissions in the UI.

This also appears to be occurring with PolyPulsar which supports both BPUL and BNT tokens

**Comment by Polypup** [comment]
This is not something that will be supported. These are highly customizable masterchefs that would be impossible to auto generate fields for.
