### ISSUE TITLE
Feature Request - Add to MetaMask

### ISSUE THREAD

**Issue by fire-farmer** [PolyPup-Farm/polypup-ui-alpha-testers#30]
I think it would be handy to have an "add to metamask" link next to the token address within the 'Token Information' section. Also, this might just be a personal preference but when viewing from mobile I'd rather not have the token address up top and see a larger farm name font. I'd prefer to see the 'save to clipboard' link also in the Token Information section. That should clean up the look quite a bit. 

![IMG_1064](https://user-images.githubusercontent.com/89096900/131415032-92364bf4-4e72-4f4e-ab2a-da6c5b7decca.jpg)

**Comment by Polypup** [comment]
Great idea. Love it. Gonna do this very soon.

**Comment by Polypup** [comment]
completed.
