### ISSUE TITLE
Balance Issue: Top Dashboard

### ISSUE THREAD

**Issue by nramos39** [PolyPup-Farm/polypup-ui-alpha-testers#33]
Balances would update after harvesting and staking in pool. Top dashboard reflecting Balance and Total Invested did not update. Had to refresh to update top info as well

**Comment by Polypup** [comment]
This is on a 30 second timer in which all data is refreshed. Nothing should ever need to be refreshed.

 I'll try and add this data to the update I did yesterday.

**Comment by Polypup** [comment]
Fixed by emitting event of new balance and pendingHarvests.
