### ISSUE TITLE
Need container to optimise viewport on smaller screens like laptops etc.

### ISSUE THREAD

**Issue by neothon** [PolyPup-Farm/polypup-ui-alpha-testers#4]
There has to be a container div with atleast width 90% so that the content doesn't stick to the edges of the screen. It works fine on a larger screen but is sticking to the edges on a laptop screen.

![image](https://user-images.githubusercontent.com/89765091/131290011-55bb97cc-945b-4d49-8169-3859d7ec37b6.png)

**Comment by Polypup** [comment]
added 95% width
